quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres.fcnsnemrgdbicmdrrhoe
quarkus.datasource.password=14082008Web@1421
quarkus.datasource.jdbc.url=jdbc:postgresql://aws-0-us-east-2.pooler.supabase.com:5432/postgres


quarkus.datasource.devservices.enabled=false


quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=true
